In [1]:
import pandas as pd
print(pd.read_csv('Machines.csv'))
print(pd.read_csv('Maintenance.csv'))
print(pd.read_csv('Quality_Inspections.csv'))
print(pd.read_csv('production.csv'))
print(pd.read_csv('products.csv'))

   machine_id machine_name   factory    installation_date   shifts  \
0        M000       CNS-00  Banglore  2026-12-24 23:40:13  Morning
1        M001       CNS-01  Karnatak  2026-07-04 14:35:29  Morning
2        M002       CNS-02       Goa  2026-02-16 18:04:09  Morning
3        M003       CNS-03       Goa  2026-07-03 11:20:15  Morning
4        M004       CNS-04       Goa  2026-03-25 18:30:15  Morning
..        ...          ...       ...                  ...      ...
95      M0095      CNS-095    Mumbai  2026-11-26 17:58:34   Nights
96      M0096      CNS-096  Karnatak  2026-07-20 12:21:37   Nights
97      M0097      CNS-097    Mumbai  2026-07-30 14:40:42   Nights
98      M0098      CNS-098       Goa  2026-09-09 21:50:27  Morning
99      M0099      CNS-099       Goa  2026-05-08 19:57:55   Nights

   production_line    status
0               L2    Active
1               L4    Active
2               L3  Inactive
3               L1  Inactive
4               L3    Active
..             ...       ...
95              L3    Active
96              L2  Inactive
97              L3    Active
98              L3  Inactive
99              L4    Active

[100 rows x 7 columns]
   maintenance_id machine_id     maintenance_date maintenance_type  \
0          MT0000       M000  2026-12-04 18:42:06       Predictive
1          MT0001       M001  2026-11-04 21:28:49       Preventive
2          MT0002       M002  2026-07-05 13:34:03       Preventive
3          MT0003       M003  2026-08-25 14:58:30       Predictive
4          MT0004       M004  2026-11-25 18:06:02       Preventive
..            ...        ...                  ...              ...
95        MT00095      M0095  2026-07-29 20:38:27       Corrective
96        MT00096      M0096  2026-11-06 23:29:55       Preventive
97        MT00097      M0097  2026-11-14 09:27:23       Corrective
98        MT00098      M0098  2026-06-23 23:03:50       Preventive
99        MT00099      M0099  2026-09-15 22:10:40       Predictive

    downtime_hours  maintenance_cost
0              2.2            5418.5
1              3.6             626.4
2              1.7             309.8
3              1.9            3360.1
4              1.3             629.9
..             ...               ...
95             8.8            9784.6
96             1.8             697.5
97             4.7           17758.5
98             2.0             379.3
99             1.1            8635.5

[100 rows x 6 columns]
   inspection_id production_id      inspection_date  inspected_units  \
0          Q0000        PR0000  2026-07-17 10:51:26              123
1          Q0001        PR0001  2026-04-01 11:04:02               53
2          Q0002        PR0002  2026-09-25 02:03:55               81
3          Q0003        PR0003  2026-06-12 05:26:49              134
4          Q0004        PR0004  2026-07-20 12:32:14               86
..           ...           ...                  ...              ...
95        Q00095       PR00095  2026-06-04 09:54:43              164
96        Q00096       PR00096  2026-07-04 23:09:18               55
97        Q00097       PR00097  2026-12-18 23:21:27               89
98        Q00098       PR00098  2026-08-24 22:52:44              143
99        Q00099       PR00099  2026-02-01 18:12:56               64

    defective_units        defect_type
0                11  Dimensional Error
1                 3     Surface Defect
2                 3     Assembly Error
3                 0     Assembly Error
4                 2     Surface Defect
..              ...                ...
95                0  Dimensional Error
96                0     Assembly Error
97                3  Dimensional Error
98               10  Dimensional Error
99                6  Dimensional Error

[100 rows x 6 columns]
   production_id machine_id product_id      production_date    shift  \
0         PR0000       M000       P000  2026-03-03 23:56:23  Morning
1         PR0001       M001       P001  2026-06-09 14:45:35  Morning
2         PR0002       M002       P002  2026-06-30 05:58:12  Morning
3         PR0003       M003       P003  2026-07-24 22:53:32  Morning
4         PR0004       M004       P004  2026-10-07 06:04:29  Morning
..           ...        ...        ...                  ...      ...
95       PR00095      M0095      P0095  2026-12-14 19:06:10   Nights
96       PR00096      M0096      P0096  2026-03-19 12:43:34   Nights
97       PR00097      M0097      P0097  2026-11-21 19:42:24   Nights
98       PR00098      M0098      P0098  2026-05-22 11:42:28  Morning
99       PR00099      M0099      P0099  2026-10-10 11:58:28   Nights

    units_produced  operating_hours
0               13               11
1               22                8
2               25                2
3               24                4
4               14                3
..             ...              ...
95              14                8
96              23               10
97              22               11
98              15               12
99              19                4

[100 rows x 7 columns]
   product_id        product_name     category  unit_cost  selling_price  \
0        P000     Hydraulic Valve   Electrical        883        1233.89
1        P001          Valve Body  Electronics       7860       10624.62
2        P002       Control Panel   Industrial       4023        5546.98
3        P003         Brake Rotor   Industrial        892        1158.40
4        P004     Hydraulic Valve   Automotive        876        1145.31
..        ...                 ...          ...        ...            ...
95      P0095   Transmission Gear   Automotive        879        1133.75
96      P0096  Alternator Housing   Mechanical       1404        1962.09
97      P0097    Bearing Assembly   Automotive       1331        1800.70
98      P0098       Motor Housing   Mechanical        474         644.00
99      P0099      Hydraulic Pump   Electrical       1281        1689.10

    standard_production_time
0                         67
1                         50
2                         70
3                        126
4                         33
..                       ...
95                        72
96                        92
97                       113
98                        97
99                        42

[100 rows x 6 columns]

In [2]:
df_Machines = pd.read_csv('Machines.csv')

In [3]:
df_Maintenance = pd.read_csv('Maintenance.csv')

In [4]:
df_QI = pd.read_csv('Quality_Inspections.csv')

In [5]:
df_production = pd.read_csv("production.csv")

In [6]:
df_products = pd.read_csv('products.csv')

In [7]:
for name,df in {
    'production':df_production,
    'Machines':df_Machines,
    'Maintenance':df_Maintenance,
    'QI':df_QI,
    'products':df_products
}.items():
    print(f"{name}")
    print(f"Shaper{df.shape}")
    print(f"Missing_Val: {df.isnull().sum()}")
    print(f"Duplicates:{df.duplicated().sum()}")
    print(f"No_of_rows:{len(df)}")
    print(f"No_of_cols:{len(df.columns)}")

production
Shaper(100, 7)
Missing_Val: production_id      0
machine_id         0
product_id         0
production_date    0
shift              0
units_produced     0
operating_hours    0
dtype: int64
Duplicates:0
No_of_rows:100
No_of_cols:7
Machines
Shaper(100, 7)
Missing_Val: machine_id           0
machine_name         0
factory              0
installation_date    0
shifts               0
production_line      0
status               0
dtype: int64
Duplicates:0
No_of_rows:100
No_of_cols:7
Maintenance
Shaper(100, 6)
Missing_Val: maintenance_id      0
machine_id          0
maintenance_date    0
maintenance_type    0
downtime_hours      0
maintenance_cost    0
dtype: int64
Duplicates:0
No_of_rows:100
No_of_cols:6
QI
Shaper(100, 6)
Missing_Val: inspection_id      0
production_id      0
inspection_date    0
inspected_units    0
defective_units    0
defect_type        0
dtype: int64
Duplicates:0
No_of_rows:100
No_of_cols:6
products
Shaper(100, 6)
Missing_Val: product_id                  0
product_name                0
category                    0
unit_cost                   0
selling_price               0
standard_production_time    0
dtype: int64
Duplicates:0
No_of_rows:100
No_of_cols:6

In [8]:
for name,df in {
    'production':df_production,
    'Machines':df_Machines,
    'Maintenance':df_Maintenance,
    'QI':df_QI,
    'products':df_products
}.items():
  print(f"""head of {name}
            {df.head(10)}""")

head of production
              production_id machine_id product_id      production_date    shift  \
0        PR0000       M000       P000  2026-03-03 23:56:23  Morning
1        PR0001       M001       P001  2026-06-09 14:45:35  Morning
2        PR0002       M002       P002  2026-06-30 05:58:12  Morning
3        PR0003       M003       P003  2026-07-24 22:53:32  Morning
4        PR0004       M004       P004  2026-10-07 06:04:29  Morning
5        PR0005       M005       P005  2026-03-14 14:22:30  Morning
6        PR0006       M006       P006  2026-02-17 12:58:09  Morning
7        PR0007       M007       P007  2026-12-12 23:02:30   Nights
8        PR0008       M008       P008  2026-10-23 16:09:05  Morning
9        PR0009       M009       P009  2026-05-17 08:02:32  Morning

   units_produced  operating_hours
0              13               11
1              22                8
2              25                2
3              24                4
4              14                3
5              12                7
6              14                8
7              10                2
8              11                5
9              21                4
head of Machines
              machine_id machine_name    factory    installation_date   shifts  \
0       M000       CNS-00   Banglore  2026-12-24 23:40:13  Morning
1       M001       CNS-01   Karnatak  2026-07-04 14:35:29  Morning
2       M002       CNS-02        Goa  2026-02-16 18:04:09  Morning
3       M003       CNS-03        Goa  2026-07-03 11:20:15  Morning
4       M004       CNS-04        Goa  2026-03-25 18:30:15  Morning
5       M005       CNS-05        Goa  2026-05-08 06:48:39  Morning
6       M006       CNS-06     Mumbai  2026-11-08 10:03:28  Morning
7       M007       CNS-07   Karnatak  2026-08-03 05:54:21   Nights
8       M008       CNS-08   Karnatak  2026-02-06 16:01:42  Morning
9       M009       CNS-09  Hyderabad  2026-04-07 12:15:11  Morning

  production_line    status
0              L2    Active
1              L4    Active
2              L3  Inactive
3              L1  Inactive
4              L3    Active
5              L1    Active
6              L4  Inactive
7              L2  Inactive
8              L4    Active
9              L4    Active
head of Maintenance
              maintenance_id machine_id     maintenance_date maintenance_type  \
0         MT0000       M000  2026-12-04 18:42:06       Predictive
1         MT0001       M001  2026-11-04 21:28:49       Preventive
2         MT0002       M002  2026-07-05 13:34:03       Preventive
3         MT0003       M003  2026-08-25 14:58:30       Predictive
4         MT0004       M004  2026-11-25 18:06:02       Preventive
5         MT0005       M005  2026-05-12 16:37:36       Corrective
6         MT0006       M006  2026-06-11 14:27:28       Predictive
7         MT0007       M007  2026-12-20 06:11:19       Corrective
8         MT0008       M008  2027-01-01 00:13:05       Preventive
9         MT0009       M009  2026-05-11 09:24:34       Predictive

   downtime_hours  maintenance_cost
0             2.2            5418.5
1             3.6             626.4
2             1.7             309.8
3             1.9            3360.1
4             1.3             629.9
5            10.5           25309.2
6             2.2            7578.6
7             7.3           21334.6
8             1.7             419.0
9             2.8            9916.5
head of QI
              inspection_id production_id      inspection_date  inspected_units  \
0         Q0000        PR0000  2026-07-17 10:51:26              123
1         Q0001        PR0001  2026-04-01 11:04:02               53
2         Q0002        PR0002  2026-09-25 02:03:55               81
3         Q0003        PR0003  2026-06-12 05:26:49              134
4         Q0004        PR0004  2026-07-20 12:32:14               86
5         Q0005        PR0005  2026-04-26 02:49:41              144
6         Q0006        PR0006  2026-01-15 11:25:18              140
7         Q0007        PR0007  2026-05-15 09:16:12              161
8         Q0008        PR0008  2026-11-18 14:24:15              188
9         Q0009        PR0009  2026-09-21 05:37:06              136

   defective_units        defect_type
0               11  Dimensional Error
1                3     Surface Defect
2                3     Assembly Error
3                0     Assembly Error
4                2     Surface Defect
5                2  Dimensional Error
6                9  Dimensional Error
7               12  Dimensional Error
8                2  Dimensional Error
9                9  Dimensional Error
head of products
              product_id     product_name     category  unit_cost  selling_price  \
0       P000  Hydraulic Valve   Electrical        883        1233.89
1       P001       Valve Body  Electronics       7860       10624.62
2       P002    Control Panel   Industrial       4023        5546.98
3       P003      Brake Rotor   Industrial        892        1158.40
4       P004  Hydraulic Valve   Automotive        876        1145.31
5       P005    Fuel Injector   Automotive        759         993.01
6       P006    Gear Assembly   Electrical       1533        1927.47
7       P007      Motor Shaft  Electronics        523         743.31
8       P008   Pressure Gauge  Electronics       6776        8694.74
9       P009   Pressure Gauge   Industrial       2484        3161.40

   standard_production_time
0                        67
1                        50
2                        70
3                       126
4                        33
5                        80
6                       114
7                        61
8                        96
9                        60

In [9]:

for i,j in {
    'production':df_production,
    'Machines':df_Machines,
    'Maintenance':df_Maintenance,
    'QI':df_QI,
    'products':df_products
}.items():
  print(i,j.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   production_id    100 non-null    object
 1   machine_id       100 non-null    object
 2   product_id       100 non-null    object
 3   production_date  100 non-null    object
 4   shift            100 non-null    object
 5   units_produced   100 non-null    int64
 6   operating_hours  100 non-null    int64
dtypes: int64(2), object(5)
memory usage: 5.6+ KB
production None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   machine_id         100 non-null    object
 1   machine_name       100 non-null    object
 2   factory            100 non-null    object
 3   installation_date  100 non-null    object
 4   shifts             100 non-null    object
 5   production_line    100 non-null    object
 6   status             100 non-null    object
dtypes: object(7)
memory usage: 5.6+ KB
Machines None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   maintenance_id    100 non-null    object
 1   machine_id        100 non-null    object
 2   maintenance_date  100 non-null    object
 3   maintenance_type  100 non-null    object
 4   downtime_hours    100 non-null    float64
 5   maintenance_cost  100 non-null    float64
dtypes: float64(2), object(4)
memory usage: 4.8+ KB
Maintenance None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   inspection_id    100 non-null    object
 1   production_id    100 non-null    object
 2   inspection_date  100 non-null    object
 3   inspected_units  100 non-null    int64
 4   defective_units  100 non-null    int64
 5   defect_type      100 non-null    object
dtypes: int64(2), object(4)
memory usage: 4.8+ KB
QI None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 6 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   product_id                100 non-null    object
 1   product_name              100 non-null    object
 2   category                  100 non-null    object
 3   unit_cost                 100 non-null    int64
 4   selling_price             100 non-null    float64
 5   standard_production_time  100 non-null    int64
dtypes: float64(1), int64(2), object(3)
memory usage: 4.8+ KB
products None

In [10]:
len(df_Machines.columns)

7

In [11]:
len(df_Maintenance.columns)

6

In [12]:
len(df_production.columns)

7

In [13]:
len(df_QI.columns)

6

In [14]:
len(df_QI)

100

In [15]:
df_QI['inspection_date'
]

0     2026-07-17 10:51:26
1     2026-04-01 11:04:02
2     2026-09-25 02:03:55
3     2026-06-12 05:26:49
4     2026-07-20 12:32:14
             ...
95    2026-06-04 09:54:43
96    2026-07-04 23:09:18
97    2026-12-18 23:21:27
98    2026-08-24 22:52:44
99    2026-02-01 18:12:56
Name: inspection_date, Length: 100, dtype: object

In [16]:
df_production.groupby("shift", as_index = False)['units_produced'].sum()

     shift  units_produced
0  Morning             771
1   Nights             960

In [17]:
df = pd.read_csv("production.csv")

In [18]:
df[df['units_produced'] > 500]

Empty DataFrame
Columns: [production_id, machine_id, product_id, production_date, shift, units_produced, operating_hours]
Index: []

In [19]:
df[(df['units_produced'] > 500) & (df['operating_hours'] > 8)]

Empty DataFrame
Columns: [production_id, machine_id, product_id, production_date, shift, units_produced, operating_hours]
Index: []

In [20]:
df.dtypes

production_id      object
machine_id         object
product_id         object
production_date    object
shift              object
units_produced      int64
operating_hours     int64
dtype: object

In [21]:
df['operating_hours']

0     11
1      8
2      2
3      4
4      3
      ..
95     8
96    10
97    11
98    12
99     4
Name: operating_hours, Length: 100, dtype: int64

In [22]:
df[df['operating_hours'] > 8]

,production_id,machine_id,product_id,production_date,shift,units_produced,operating_hours
0,PR0000,M000,P000,2026-03-03 23:56:23,Morning,13,11
10,PR00010,M0010,P0010,2026-12-10 01:52:07,Nights,21,10
14,PR00014,M0014,P0014,2026-05-01 17:38:59,Nights,23,10
15,PR00015,M0015,P0015,2026-12-25 18:05:34,Morning,14,10
18,PR00018,M0018,P0018,2026-03-10 13:44:34,Morning,14,10
19,PR00019,M0019,P0019,2026-12-11 23:58:55,Nights,14,9
28,PR00028,M0028,P0028,2026-05-30 04:52:31,Nights,11,11
30,PR00030,M0030,P0030,2026-09-05 03:22:58,Nights,14,12
35,PR00035,M0035,P0035,2026-05-29 09:21:21,Morning,23,9
36,PR00036,M0036,P0036,2026-04-14 13:51:03,Morning,24,10
38,PR00038,M0038,P0038,2026-12-15 09:21:41,Nights,18,12
39,PR00039,M0039,P0039,2026-12-09 11:14:07,Nights,18,12
45,PR00045,M0045,P0045,2026-04-24 08:09:19,Nights,16,11
47,PR00047,M0047,P0047,2026-11-05 13:09:20,Nights,23,9
50,PR00050,M0050,P0050,2026-08-24 21:31:12,Nights,15,9
54,PR00054,M0054,P0054,2026-09-05 20:32:12,Morning,18,12
56,PR00056,M0056,P0056,2026-08-01 11:16:26,Nights,12,10
57,PR00057,M0057,P0057,2026-03-20 05:11:27,Nights,20,9
60,PR00060,M0060,P0060,2026-04-10 16:13:48,Morning,12,11
61,PR00061,M0061,P0061,2026-10-02 02:07:41,Morning,22,9
63,PR00063,M0063,P0063,2026-10-16 08:45:28,Nights,19,12
69,PR00069,M0069,P0069,2026-09-11 11:45:23,Morning,21,12
70,PR00070,M0070,P0070,2026-12-05 21:17:53,Morning,10,11
71,PR00071,M0071,P0071,2026-12-30 08:14:27,Nights,10,12
72,PR00072,M0072,P0072,2026-01-09 13:30:12,Nights,15,10
74,PR00074,M0074,P0074,2026-02-15 00:09:34,Nights,17,11
75,PR00075,M0075,P0075,2026-02-01 05:52:10,Morning,22,11
76,PR00076,M0076,P0076,2026-06-27 06:37:00,Morning,12,12
77,PR00077,M0077,P0077,2026-02-18 17:28:40,Nights,25,12
78,PR00078,M0078,P0078,2026-05-28 00:44:28,Nights,13,12
80,PR00080,M0080,P0080,2026-02-13 16:11:47,Morning,20,12
82,PR00082,M0082,P0082,2026-06-18 20:40:28,Nights,18,11
83,PR00083,M0083,P0083,2026-06-29 11:39:34,Morning,11,10
86,PR00086,M0086,P0086,2026-10-07 17:45:45,Morning,13,10
90,PR00090,M0090,P0090,2026-04-21 08:27:25,Morning,24,9
91,PR00091,M0091,P0091,2026-07-09 03:14:35,Morning,19,12
94,PR00094,M0094,P0094,2026-06-11 00:31:25,Nights,25,12
96,PR00096,M0096,P0096,2026-03-19 12:43:34,Nights,23,10
97,PR00097,M0097,P0097,2026-11-21 19:42:24,Nights,22,11
98,PR00098,M0098,P0098,2026-05-22 11:42:28,Morning,15,12

In [23]:
df[df['shift'].isin(["Morning","Nights"])]

,production_id,machine_id,product_id,production_date,shift,units_produced,operating_hours
0,PR0000,M000,P000,2026-03-03 23:56:23,Morning,13,11
1,PR0001,M001,P001,2026-06-09 14:45:35,Morning,22,8
2,PR0002,M002,P002,2026-06-30 05:58:12,Morning,25,2
3,PR0003,M003,P003,2026-07-24 22:53:32,Morning,24,4
4,PR0004,M004,P004,2026-10-07 06:04:29,Morning,14,3
...,...,...,...,...,...,...,...
95,PR00095,M0095,P0095,2026-12-14 19:06:10,Nights,14,8
96,PR00096,M0096,P0096,2026-03-19 12:43:34,Nights,23,10
97,PR00097,M0097,P0097,2026-11-21 19:42:24,Nights,22,11
98,PR00098,M0098,P0098,2026-05-22 11:42:28,Morning,15,12
99,PR00099,M0099,P0099,2026-10-10 11:58:28,Nights,19,4

In [24]:
df['production_date'] = pd.to_datetime(df['production_date'], format= "mixed")
df.dtypes

production_id              object
machine_id                 object
product_id                 object
production_date    datetime64[ns]
shift                      object
units_produced              int64
operating_hours             int64
dtype: object

In [25]:
# df[df["column"].between(low,high)]
df[df['units_produced'].between(400,600)]

Empty DataFrame
Columns: [production_id, machine_id, product_id, production_date, shift, units_produced, operating_hours]
Index: []

In [26]:
df[df['units_produced'] < 400]

,production_id,machine_id,product_id,production_date,shift,units_produced,operating_hours
0,PR0000,M000,P000,2026-03-03 23:56:23,Morning,13,11
1,PR0001,M001,P001,2026-06-09 14:45:35,Morning,22,8
2,PR0002,M002,P002,2026-06-30 05:58:12,Morning,25,2
3,PR0003,M003,P003,2026-07-24 22:53:32,Morning,24,4
4,PR0004,M004,P004,2026-10-07 06:04:29,Morning,14,3
...,...,...,...,...,...,...,...
95,PR00095,M0095,P0095,2026-12-14 19:06:10,Nights,14,8
96,PR00096,M0096,P0096,2026-03-19 12:43:34,Nights,23,10
97,PR00097,M0097,P0097,2026-11-21 19:42:24,Nights,22,11
98,PR00098,M0098,P0098,2026-05-22 11:42:28,Morning,15,12
99,PR00099,M0099,P0099,2026-10-10 11:58:28,Nights,19,4

In [27]:
df['units_produced']

0     13
1     22
2     25
3     24
4     14
      ..
95    14
96    23
97    22
98    15
99    19
Name: units_produced, Length: 100, dtype: int64

In [28]:
#Find all production records where units_produced is greater than 100.
df['units_produced'] > 100

0     False
1     False
2     False
3     False
4     False
      ...
95    False
96    False
97    False
98    False
99    False
Name: units_produced, Length: 100, dtype: bool

In [29]:
df.groupby('shift')['units_produced'].sum()

shift
Morning    771
Nights     960
Name: units_produced, dtype: int64

In [30]:
df

,production_id,machine_id,product_id,production_date,shift,units_produced,operating_hours
0,PR0000,M000,P000,2026-03-03 23:56:23,Morning,13,11
1,PR0001,M001,P001,2026-06-09 14:45:35,Morning,22,8
2,PR0002,M002,P002,2026-06-30 05:58:12,Morning,25,2
3,PR0003,M003,P003,2026-07-24 22:53:32,Morning,24,4
4,PR0004,M004,P004,2026-10-07 06:04:29,Morning,14,3
...,...,...,...,...,...,...,...
95,PR00095,M0095,P0095,2026-12-14 19:06:10,Nights,14,8
96,PR00096,M0096,P0096,2026-03-19 12:43:34,Nights,23,10
97,PR00097,M0097,P0097,2026-11-21 19:42:24,Nights,22,11
98,PR00098,M0098,P0098,2026-05-22 11:42:28,Morning,15,12
99,PR00099,M0099,P0099,2026-10-10 11:58:28,Nights,19,4

In [31]:
#From production, find every record where units_produced is greater than 100
df[df['units_produced'] > 100]

Empty DataFrame
Columns: [production_id, machine_id, product_id, production_date, shift, units_produced, operating_hours]
Index: []

In [32]:
df[df["units_produced"] > 100]

Empty DataFrame
Columns: [production_id, machine_id, product_id, production_date, shift, units_produced, operating_hours]
Index: []

In [33]:
#Find records where units_produced > 100 AND operating_hours > 6.
df[(df["units_produced"] > 100) & (df['operating_hours'] > 6)]

Empty DataFrame
Columns: [production_id, machine_id, product_id, production_date, shift, units_produced, operating_hours]
Index: []

In [34]:
#Find records where shift is either "Morning" or "Nights".
df[(df['shift'] == 'Morning') | (df['shift'] == "Nights")]

,production_id,machine_id,product_id,production_date,shift,units_produced,operating_hours
0,PR0000,M000,P000,2026-03-03 23:56:23,Morning,13,11
1,PR0001,M001,P001,2026-06-09 14:45:35,Morning,22,8
2,PR0002,M002,P002,2026-06-30 05:58:12,Morning,25,2
3,PR0003,M003,P003,2026-07-24 22:53:32,Morning,24,4
4,PR0004,M004,P004,2026-10-07 06:04:29,Morning,14,3
...,...,...,...,...,...,...,...
95,PR00095,M0095,P0095,2026-12-14 19:06:10,Nights,14,8
96,PR00096,M0096,P0096,2026-03-19 12:43:34,Nights,23,10
97,PR00097,M0097,P0097,2026-11-21 19:42:24,Nights,22,11
98,PR00098,M0098,P0098,2026-05-22 11:42:28,Morning,15,12
99,PR00099,M0099,P0099,2026-10-10 11:58:28,Nights,19,4

In [35]:
df[df['shift'].isin(['Morning','Nights'])]

,production_id,machine_id,product_id,production_date,shift,units_produced,operating_hours
0,PR0000,M000,P000,2026-03-03 23:56:23,Morning,13,11
1,PR0001,M001,P001,2026-06-09 14:45:35,Morning,22,8
2,PR0002,M002,P002,2026-06-30 05:58:12,Morning,25,2
3,PR0003,M003,P003,2026-07-24 22:53:32,Morning,24,4
4,PR0004,M004,P004,2026-10-07 06:04:29,Morning,14,3
...,...,...,...,...,...,...,...
95,PR00095,M0095,P0095,2026-12-14 19:06:10,Nights,14,8
96,PR00096,M0096,P0096,2026-03-19 12:43:34,Nights,23,10
97,PR00097,M0097,P0097,2026-11-21 19:42:24,Nights,22,11
98,PR00098,M0098,P0098,2026-05-22 11:42:28,Morning,15,12
99,PR00099,M0099,P0099,2026-10-10 11:58:28,Nights,19,4

In [36]:
#Find production records where units_produced is between 80 and 120, inclusive.
df[df['units_produced'].between(80,120)]

Empty DataFrame
Columns: [production_id, machine_id, product_id, production_date, shift, units_produced, operating_hours]
Index: []

In [37]:
#Find the total units_produced for each shift.
df.groupby('shift')['units_produced'].sum()

shift
Morning    771
Nights     960
Name: units_produced, dtype: int64

In [38]:
#Find the maximum units_produced for each shift.
df.groupby('shift')['units_produced'].max()

shift
Morning    25
Nights     25
Name: units_produced, dtype: int64

In [39]:
#For each shift → total, average, minimum, maximum units_produced.
df.groupby('shift')['units_produced'].agg(['sum','mean','min','max'])

         sum       mean  min  max
shift
Morning  771  16.404255   10   25
Nights   960  18.113208   10   25

In [40]:
#Show every production record together with the factory where that machine operates.
df

,production_id,machine_id,product_id,production_date,shift,units_produced,operating_hours
0,PR0000,M000,P000,2026-03-03 23:56:23,Morning,13,11
1,PR0001,M001,P001,2026-06-09 14:45:35,Morning,22,8
2,PR0002,M002,P002,2026-06-30 05:58:12,Morning,25,2
3,PR0003,M003,P003,2026-07-24 22:53:32,Morning,24,4
4,PR0004,M004,P004,2026-10-07 06:04:29,Morning,14,3
...,...,...,...,...,...,...,...
95,PR00095,M0095,P0095,2026-12-14 19:06:10,Nights,14,8
96,PR00096,M0096,P0096,2026-03-19 12:43:34,Nights,23,10
97,PR00097,M0097,P0097,2026-11-21 19:42:24,Nights,22,11
98,PR00098,M0098,P0098,2026-05-22 11:42:28,Morning,15,12
99,PR00099,M0099,P0099,2026-10-10 11:58:28,Nights,19,4

In [42]:
df_production.merge(df_Machines, on = 'machine_id')

,production_id,machine_id,product_id,production_date,shift,units_produced,operating_hours,machine_name,factory,installation_date,shifts,production_line,status
0,PR0000,M000,P000,2026-03-03 23:56:23,Morning,13,11,CNS-00,Banglore,2026-12-24 23:40:13,Morning,L2,Active
1,PR0001,M001,P001,2026-06-09 14:45:35,Morning,22,8,CNS-01,Karnatak,2026-07-04 14:35:29,Morning,L4,Active
2,PR0002,M002,P002,2026-06-30 05:58:12,Morning,25,2,CNS-02,Goa,2026-02-16 18:04:09,Morning,L3,Inactive
3,PR0003,M003,P003,2026-07-24 22:53:32,Morning,24,4,CNS-03,Goa,2026-07-03 11:20:15,Morning,L1,Inactive
4,PR0004,M004,P004,2026-10-07 06:04:29,Morning,14,3,CNS-04,Goa,2026-03-25 18:30:15,Morning,L3,Active
...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,PR00095,M0095,P0095,2026-12-14 19:06:10,Nights,14,8,CNS-095,Mumbai,2026-11-26 17:58:34,Nights,L3,Active
96,PR00096,M0096,P0096,2026-03-19 12:43:34,Nights,23,10,CNS-096,Karnatak,2026-07-20 12:21:37,Nights,L2,Inactive
97,PR00097,M0097,P0097,2026-11-21 19:42:24,Nights,22,11,CNS-097,Mumbai,2026-07-30 14:40:42,Nights,L3,Active
98,PR00098,M0098,P0098,2026-05-22 11:42:28,Morning,15,12,CNS-098,Goa,2026-09-09 21:50:27,Morning,L3,Inactive
99,PR00099,M0099,P0099,2026-10-10 11:58:28,Nights,19,4,CNS-099,Goa,2026-05-08 19:57:55,Nights,L4,Active

In [43]:
df_production

,production_id,machine_id,product_id,production_date,shift,units_produced,operating_hours
0,PR0000,M000,P000,2026-03-03 23:56:23,Morning,13,11
1,PR0001,M001,P001,2026-06-09 14:45:35,Morning,22,8
2,PR0002,M002,P002,2026-06-30 05:58:12,Morning,25,2
3,PR0003,M003,P003,2026-07-24 22:53:32,Morning,24,4
4,PR0004,M004,P004,2026-10-07 06:04:29,Morning,14,3
...,...,...,...,...,...,...,...
95,PR00095,M0095,P0095,2026-12-14 19:06:10,Nights,14,8
96,PR00096,M0096,P0096,2026-03-19 12:43:34,Nights,23,10
97,PR00097,M0097,P0097,2026-11-21 19:42:24,Nights,22,11
98,PR00098,M0098,P0098,2026-05-22 11:42:28,Morning,15,12
99,PR00099,M0099,P0099,2026-10-10 11:58:28,Nights,19,4

In [44]:
df_Machines

,machine_id,machine_name,factory,installation_date,shifts,production_line,status
0,M000,CNS-00,Banglore,2026-12-24 23:40:13,Morning,L2,Active
1,M001,CNS-01,Karnatak,2026-07-04 14:35:29,Morning,L4,Active
2,M002,CNS-02,Goa,2026-02-16 18:04:09,Morning,L3,Inactive
3,M003,CNS-03,Goa,2026-07-03 11:20:15,Morning,L1,Inactive
4,M004,CNS-04,Goa,2026-03-25 18:30:15,Morning,L3,Active
...,...,...,...,...,...,...,...
95,M0095,CNS-095,Mumbai,2026-11-26 17:58:34,Nights,L3,Active
96,M0096,CNS-096,Karnatak,2026-07-20 12:21:37,Nights,L2,Inactive
97,M0097,CNS-097,Mumbai,2026-07-30 14:40:42,Nights,L3,Active
98,M0098,CNS-098,Goa,2026-09-09 21:50:27,Morning,L3,Inactive
99,M0099,CNS-099,Goa,2026-05-08 19:57:55,Nights,L4,Active

In [45]:
df_production.merge(df_Machines, on = 'machine_id')

,production_id,machine_id,product_id,production_date,shift,units_produced,operating_hours,machine_name,factory,installation_date,shifts,production_line,status
0,PR0000,M000,P000,2026-03-03 23:56:23,Morning,13,11,CNS-00,Banglore,2026-12-24 23:40:13,Morning,L2,Active
1,PR0001,M001,P001,2026-06-09 14:45:35,Morning,22,8,CNS-01,Karnatak,2026-07-04 14:35:29,Morning,L4,Active
2,PR0002,M002,P002,2026-06-30 05:58:12,Morning,25,2,CNS-02,Goa,2026-02-16 18:04:09,Morning,L3,Inactive
3,PR0003,M003,P003,2026-07-24 22:53:32,Morning,24,4,CNS-03,Goa,2026-07-03 11:20:15,Morning,L1,Inactive
4,PR0004,M004,P004,2026-10-07 06:04:29,Morning,14,3,CNS-04,Goa,2026-03-25 18:30:15,Morning,L3,Active
...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,PR00095,M0095,P0095,2026-12-14 19:06:10,Nights,14,8,CNS-095,Mumbai,2026-11-26 17:58:34,Nights,L3,Active
96,PR00096,M0096,P0096,2026-03-19 12:43:34,Nights,23,10,CNS-096,Karnatak,2026-07-20 12:21:37,Nights,L2,Inactive
97,PR00097,M0097,P0097,2026-11-21 19:42:24,Nights,22,11,CNS-097,Mumbai,2026-07-30 14:40:42,Nights,L3,Active
98,PR00098,M0098,P0098,2026-05-22 11:42:28,Morning,15,12,CNS-098,Goa,2026-09-09 21:50:27,Morning,L3,Inactive
99,PR00099,M0099,P0099,2026-10-10 11:58:28,Nights,19,4,CNS-099,Goa,2026-05-08 19:57:55,Nights,L4,Active

In [46]:
#Keep every production record, and bring matching machine information from df_Machines.
df_production.merge(df_Machines, on = 'machine_id',how = 'left')

,production_id,machine_id,product_id,production_date,shift,units_produced,operating_hours,machine_name,factory,installation_date,shifts,production_line,status
0,PR0000,M000,P000,2026-03-03 23:56:23,Morning,13,11,CNS-00,Banglore,2026-12-24 23:40:13,Morning,L2,Active
1,PR0001,M001,P001,2026-06-09 14:45:35,Morning,22,8,CNS-01,Karnatak,2026-07-04 14:35:29,Morning,L4,Active
2,PR0002,M002,P002,2026-06-30 05:58:12,Morning,25,2,CNS-02,Goa,2026-02-16 18:04:09,Morning,L3,Inactive
3,PR0003,M003,P003,2026-07-24 22:53:32,Morning,24,4,CNS-03,Goa,2026-07-03 11:20:15,Morning,L1,Inactive
4,PR0004,M004,P004,2026-10-07 06:04:29,Morning,14,3,CNS-04,Goa,2026-03-25 18:30:15,Morning,L3,Active
...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,PR00095,M0095,P0095,2026-12-14 19:06:10,Nights,14,8,CNS-095,Mumbai,2026-11-26 17:58:34,Nights,L3,Active
96,PR00096,M0096,P0096,2026-03-19 12:43:34,Nights,23,10,CNS-096,Karnatak,2026-07-20 12:21:37,Nights,L2,Inactive
97,PR00097,M0097,P0097,2026-11-21 19:42:24,Nights,22,11,CNS-097,Mumbai,2026-07-30 14:40:42,Nights,L3,Active
98,PR00098,M0098,P0098,2026-05-22 11:42:28,Morning,15,12,CNS-098,Goa,2026-09-09 21:50:27,Morning,L3,Inactive
99,PR00099,M0099,P0099,2026-10-10 11:58:28,Nights,19,4,CNS-099,Goa,2026-05-08 19:57:55,Nights,L4,Active

In [47]:
#Calculate the production rate for every production record.
#df["NEW COLUMN"] = units_produced / operating_hours
x =df["units_produced"]/df["operating_hours"]
df['production_rate'] = x

In [48]:
df

,production_id,machine_id,product_id,production_date,shift,units_produced,operating_hours,production_rate
0,PR0000,M000,P000,2026-03-03 23:56:23,Morning,13,11,1.181818
1,PR0001,M001,P001,2026-06-09 14:45:35,Morning,22,8,2.750000
2,PR0002,M002,P002,2026-06-30 05:58:12,Morning,25,2,12.500000
3,PR0003,M003,P003,2026-07-24 22:53:32,Morning,24,4,6.000000
4,PR0004,M004,P004,2026-10-07 06:04:29,Morning,14,3,4.666667
...,...,...,...,...,...,...,...,...
95,PR00095,M0095,P0095,2026-12-14 19:06:10,Nights,14,8,1.750000
96,PR00096,M0096,P0096,2026-03-19 12:43:34,Nights,23,10,2.300000
97,PR00097,M0097,P0097,2026-11-21 19:42:24,Nights,22,11,2.000000
98,PR00098,M0098,P0098,2026-05-22 11:42:28,Morning,15,12,1.250000
99,PR00099,M0099,P0099,2026-10-10 11:58:28,Nights,19,4,4.750000

In [55]:
#Using df_production, create a new column called defect_rate using:
#defective_units / inspected_units ×
#y =  (
  #  df_production["defective_units"] /
 #   df_production["inspected_units"] * 100
#)
#df_production["defect_rate"] = y

In [57]:
df_production[df_production['units_produced'] > 100]

Empty DataFrame
Columns: [production_id, machine_id, product_id, production_date, shift, units_produced, operating_hours]
Index: []

In [58]:
df_production[(df_production['units_produced'] > 100) &(df_production['operating_hours'] > 6) ]

Empty DataFrame
Columns: [production_id, machine_id, product_id, production_date, shift, units_produced, operating_hours]
Index: []

In [60]:
df_production[df_production['shift'].isin(["Morning",'Nights'])]

,production_id,machine_id,product_id,production_date,shift,units_produced,operating_hours
0,PR0000,M000,P000,2026-03-03 23:56:23,Morning,13,11
1,PR0001,M001,P001,2026-06-09 14:45:35,Morning,22,8
2,PR0002,M002,P002,2026-06-30 05:58:12,Morning,25,2
3,PR0003,M003,P003,2026-07-24 22:53:32,Morning,24,4
4,PR0004,M004,P004,2026-10-07 06:04:29,Morning,14,3
...,...,...,...,...,...,...,...
95,PR00095,M0095,P0095,2026-12-14 19:06:10,Nights,14,8
96,PR00096,M0096,P0096,2026-03-19 12:43:34,Nights,23,10
97,PR00097,M0097,P0097,2026-11-21 19:42:24,Nights,22,11
98,PR00098,M0098,P0098,2026-05-22 11:42:28,Morning,15,12
99,PR00099,M0099,P0099,2026-10-10 11:58:28,Nights,19,4

In [61]:
df_production[df_production['units_produced'].between(80,120)]

Empty DataFrame
Columns: [production_id, machine_id, product_id, production_date, shift, units_produced, operating_hours]
Index: []

In [62]:
df_production.groupby('shift')['units_produced'].sum()

shift
Morning    771
Nights     960
Name: units_produced, dtype: int64

In [65]:
df_production.groupby('shift')['operating_hours'].mean()

shift
Morning    7.234043
Nights     7.339623
Name: operating_hours, dtype: float64

In [66]:
df_production.groupby('shift')['units_produced'].max()

shift
Morning    25
Nights     25
Name: units_produced, dtype: int64

In [71]:
df_production.groupby("shift")["units_produced"].agg(
    ["sum", "mean", "min", "max"]
)

         sum       mean  min  max
shift
Morning  771  16.404255   10   25
Nights   960  18.113208   10   25

In [72]:
#11. Merge df_production with df_Machines using machine_id, keeping every production record.
df_production.merge(df_Machines, on = 'machine_id')

,production_id,machine_id,product_id,production_date,shift,units_produced,operating_hours,machine_name,factory,installation_date,shifts,production_line,status
0,PR0000,M000,P000,2026-03-03 23:56:23,Morning,13,11,CNS-00,Banglore,2026-12-24 23:40:13,Morning,L2,Active
1,PR0001,M001,P001,2026-06-09 14:45:35,Morning,22,8,CNS-01,Karnatak,2026-07-04 14:35:29,Morning,L4,Active
2,PR0002,M002,P002,2026-06-30 05:58:12,Morning,25,2,CNS-02,Goa,2026-02-16 18:04:09,Morning,L3,Inactive
3,PR0003,M003,P003,2026-07-24 22:53:32,Morning,24,4,CNS-03,Goa,2026-07-03 11:20:15,Morning,L1,Inactive
4,PR0004,M004,P004,2026-10-07 06:04:29,Morning,14,3,CNS-04,Goa,2026-03-25 18:30:15,Morning,L3,Active
...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,PR00095,M0095,P0095,2026-12-14 19:06:10,Nights,14,8,CNS-095,Mumbai,2026-11-26 17:58:34,Nights,L3,Active
96,PR00096,M0096,P0096,2026-03-19 12:43:34,Nights,23,10,CNS-096,Karnatak,2026-07-20 12:21:37,Nights,L2,Inactive
97,PR00097,M0097,P0097,2026-11-21 19:42:24,Nights,22,11,CNS-097,Mumbai,2026-07-30 14:40:42,Nights,L3,Active
98,PR00098,M0098,P0098,2026-05-22 11:42:28,Morning,15,12,CNS-098,Goa,2026-09-09 21:50:27,Morning,L3,Inactive
99,PR00099,M0099,P0099,2026-10-10 11:58:28,Nights,19,4,CNS-099,Goa,2026-05-08 19:57:55,Nights,L4,Active

In [82]:
#Find the average production rate for each shift, considering only records where units_produced > 100.

df_production[df_production["units_produced"] > 100].groupby("shift")["production_rate"].mean()

Series([], Name: production_rate, dtype: float64)

In [83]:
df_production['production_rate'] = (df['units_produced'] / df['operating_hours'])

In [84]:
df_production

,production_id,machine_id,product_id,production_date,shift,units_produced,operating_hours,production_rate
0,PR0000,M000,P000,2026-03-03 23:56:23,Morning,13,11,1.181818
1,PR0001,M001,P001,2026-06-09 14:45:35,Morning,22,8,2.750000
2,PR0002,M002,P002,2026-06-30 05:58:12,Morning,25,2,12.500000
3,PR0003,M003,P003,2026-07-24 22:53:32,Morning,24,4,6.000000
4,PR0004,M004,P004,2026-10-07 06:04:29,Morning,14,3,4.666667
...,...,...,...,...,...,...,...,...
95,PR00095,M0095,P0095,2026-12-14 19:06:10,Nights,14,8,1.750000
96,PR00096,M0096,P0096,2026-03-19 12:43:34,Nights,23,10,2.300000
97,PR00097,M0097,P0097,2026-11-21 19:42:24,Nights,22,11,2.000000
98,PR00098,M0098,P0098,2026-05-22 11:42:28,Morning,15,12,1.250000
99,PR00099,M0099,P0099,2026-10-10 11:58:28,Nights,19,4,4.750000