In [1]:
#Machines.csv

In [3]:
machine_id = [f"M00{x}" for x in range(100)]
machine_name = [f"CNS-0{x}" for x in range(100)]
import random
factory_place = ["Hyderabad","Mumbai","Goa","Banglore","Karnatak"]
factory = [random.choice(factory_place) for _ in range(100)]
import pandas as pd
import numpy as np

# Define range and number of dates
start_date = pd.to_datetime('2026-01-01')
end_date = pd.to_datetime('2026-12-31')
num_dates = 100

# Generate installation_date using unix timestamps
start_u = start_date.value // 10**9
end_u = end_date.value // 10**9
random_timestamps = np.random.randint(start_u, end_u, num_dates)
installation_date = pd.to_datetime(random_timestamps, unit='s')

#shift Morning
shifs = ["Morning","Nights"]
shifts = [random.choice(shifs) for x in range(100)]

# production_line 
production_l = ["L1","L2",'L3',"L4"]
production_line = [ random.choice(production_l) for x in range(100)]

#status
state = ["Active","Inactive"]
status = [random.choice(state) for x in range(100)]

In [32]:
machinary = pd.DataFrame({
    "machine_id":machine_id,
    "machine_name":machine_name,
    "factory":factory,
    "installation_date":installation_date,
    "shifts":shifts,
    "production_line":production_line,
    "status":status
})
machinary

,machine_id,machine_name,factory,installation_date,shifts,production_line,status
0,M000,CNS-00,Banglore,2026-12-24 23:40:13,Morning,L2,Active
1,M001,CNS-01,Karnatak,2026-07-04 14:35:29,Morning,L4,Active
2,M002,CNS-02,Goa,2026-02-16 18:04:09,Morning,L3,Inactive
3,M003,CNS-03,Goa,2026-07-03 11:20:15,Morning,L1,Inactive
4,M004,CNS-04,Goa,2026-03-25 18:30:15,Morning,L3,Active
...,...,...,...,...,...,...,...
95,M0095,CNS-095,Mumbai,2026-11-26 17:58:34,Nights,L3,Active
96,M0096,CNS-096,Karnatak,2026-07-20 12:21:37,Nights,L2,Inactive
97,M0097,CNS-097,Mumbai,2026-07-30 14:40:42,Nights,L3,Active
98,M0098,CNS-098,Goa,2026-09-09 21:50:27,Morning,L3,Inactive
99,M0099,CNS-099,Goa,2026-05-08 19:57:55,Nights,L4,Active

In [33]:
machinary.to_csv("Machines.csv", index= False)

In [34]:
pd.read_csv("Machines.csv")

,machine_id,machine_name,factory,installation_date,shifts,production_line,status
0,M000,CNS-00,Banglore,2026-12-24 23:40:13,Morning,L2,Active
1,M001,CNS-01,Karnatak,2026-07-04 14:35:29,Morning,L4,Active
2,M002,CNS-02,Goa,2026-02-16 18:04:09,Morning,L3,Inactive
3,M003,CNS-03,Goa,2026-07-03 11:20:15,Morning,L1,Inactive
4,M004,CNS-04,Goa,2026-03-25 18:30:15,Morning,L3,Active
...,...,...,...,...,...,...,...
95,M0095,CNS-095,Mumbai,2026-11-26 17:58:34,Nights,L3,Active
96,M0096,CNS-096,Karnatak,2026-07-20 12:21:37,Nights,L2,Inactive
97,M0097,CNS-097,Mumbai,2026-07-30 14:40:42,Nights,L3,Active
98,M0098,CNS-098,Goa,2026-09-09 21:50:27,Morning,L3,Inactive
99,M0099,CNS-099,Goa,2026-05-08 19:57:55,Nights,L4,Active

In [35]:
#products.csv

# product_id
# product_name
# category
# unit_cost
# selling_price
# standard_production_time

In [56]:
product_id = [f"P00{x}" for x in range(100)]
 

product_name = [
    "Gear Assembly",
    "Motor Housing",
    "Valve Body",
    "Brake Rotor",
    "Control Panel",
    "Pump Housing",
    "Steel Bracket",
    "Sensor Module",
    "Hydraulic Valve",
    "Drive Shaft",
    "Bearing Assembly",
    "Fuel Injector",
    "Circuit Board",
    "Pressure Gauge",
    "Alternator Housing",
    "Transmission Gear",
    "Cooling Fan",
    "PLC Controller",
    "Hydraulic Pump",
    "Motor Shaft"
]
product_names = [random.choice(product_name) for x in range(100)]

categ = [
    "Mechanical",
    "Electrical",
    "Industrial",
    "Automotive",
    "Electronics",
    "Mechanical",
    "Automotive",
    "Electronics",
    "Industrial",
    "Mechanical",
    "Mechanical",
    "Automotive",
    "Electronics",
    "Industrial",
    "Electrical",
    "Automotive",
    "Electrical",
    "Electronics",
    "Industrial",
    "Mechanical"
]
category = [random.choice(categ) for x in range(100)]


cost_range = {
    "Mechanical": (400, 2500),
    "Electrical": (700, 3500),
    "Industrial": (500, 5000),
    "Automotive": (500, 3000),
    "Electronics": (500, 8000)
}

unit_cost = [
    random.randint(cost_range[c][0], cost_range[c][1])
    for c in category 
]

#price
selling_price = [
    round(cost * random.uniform(1.25,1.45),2)
    for cost in unit_cost
]

production_time = {
    "Mechanical":(30,120),
    "Electrical": (40,120),
    "Industrial":(45,150),
    "Automotive":(30,120),
    "Electronics":(20,100)
}

standard_production_time = [
    random.randint(production_time[p][0],production_time[p][1])
    for p in category
]

In [60]:
product_id

['P000',
 'P001',
 'P002',
 'P003',
 'P004',
 'P005',
 'P006',
 'P007',
 'P008',
 'P009',
 'P0010',
 'P0011',
 'P0012',
 'P0013',
 'P0014',
 'P0015',
 'P0016',
 'P0017',
 'P0018',
 'P0019',
 'P0020',
 'P0021',
 'P0022',
 'P0023',
 'P0024',
 'P0025',
 'P0026',
 'P0027',
 'P0028',
 'P0029',
 'P0030',
 'P0031',
 'P0032',
 'P0033',
 'P0034',
 'P0035',
 'P0036',
 'P0037',
 'P0038',
 'P0039',
 'P0040',
 'P0041',
 'P0042',
 'P0043',
 'P0044',
 'P0045',
 'P0046',
 'P0047',
 'P0048',
 'P0049',
 'P0050',
 'P0051',
 'P0052',
 'P0053',
 'P0054',
 'P0055',
 'P0056',
 'P0057',
 'P0058',
 'P0059',
 'P0060',
 'P0061',
 'P0062',
 'P0063',
 'P0064',
 'P0065',
 'P0066',
 'P0067',
 'P0068',
 'P0069',
 'P0070',
 'P0071',
 'P0072',
 'P0073',
 'P0074',
 'P0075',
 'P0076',
 'P0077',
 'P0078',
 'P0079',
 'P0080',
 'P0081',
 'P0082',
 'P0083',
 'P0084',
 'P0085',
 'P0086',
 'P0087',
 'P0088',
 'P0089',
 'P0090',
 'P0091',
 'P0092',
 'P0093',
 'P0094',
 'P0095',
 'P0096',
 'P0097',
 'P0098',
 'P0099']

In [57]:
products = pd.DataFrame(
    {
        'product_id':product_id,
        'product_name':product_names,
        'category':category,
        "unit_cost":unit_cost,
      'selling_price':selling_price,
      "standard_production_time":standard_production_time  
    }
)

products

,product_id,product_name,category,unit_cost,selling_price,standard_production_time
0,P000,Hydraulic Valve,Electrical,883,1233.89,67
1,P001,Valve Body,Electronics,7860,10624.62,50
2,P002,Control Panel,Industrial,4023,5546.98,70
3,P003,Brake Rotor,Industrial,892,1158.40,126
4,P004,Hydraulic Valve,Automotive,876,1145.31,33
...,...,...,...,...,...,...
95,P0095,Transmission Gear,Automotive,879,1133.75,72
96,P0096,Alternator Housing,Mechanical,1404,1962.09,92
97,P0097,Bearing Assembly,Automotive,1331,1800.70,113
98,P0098,Motor Housing,Mechanical,474,644.00,97
99,P0099,Hydraulic Pump,Electrical,1281,1689.10,42

In [58]:
products.to_csv("products.csv",index= False)

In [59]:
#Production
# production_id
# machine_id
# product_id
# production_date
# shift
# units_produced
# operating_hours

In [31]:
production_id = [f'PR000{x}' for x in range(100)]
operating_hours = [
    round(random.randint(2,12),2)
    for o in range(100)
]

units_produced = [
    round(random.randint(10,25),2)
    for u in operating_hours
]

start_date = pd.to_datetime('2026-01-01')
end_date = pd.to_datetime('2026-12-31')
num_dates = 100

# Generate installation_date using unix timestamps
start_u = start_date.value // 10**9
end_u = end_date.value // 10**9
random_timestamps = np.random.randint(start_u, end_u, num_dates)
production_date = pd.to_datetime(random_timestamps, unit='s')

In [32]:
production = pd.DataFrame({
    "production_id":production_id,
    "production_id":production_id,
    "machine_id":machine_id,
    "product_id":product_id,
    "production_date":production_date,
    "shift":shifts,
    "units_produced":units_produced,
    "operating_hours":operating_hours
})

production.to_csv("production.csv",index= False)

NameError: name 'product_id' is not defined

In [65]:
pd.read_csv("production.csv")

,production_id,machine_id,product_id,production_date,shift,units_produced,operating_hours
0,PR0000,M000,P000,2026-03-03 23:56:23,Morning,13,11
1,PR0001,M001,P001,2026-06-09 14:45:35,Morning,22,8
2,PR0002,M002,P002,2026-06-30 05:58:12,Morning,25,2
3,PR0003,M003,P003,2026-07-24 22:53:32,Morning,24,4
4,PR0004,M004,P004,2026-10-07 06:04:29,Morning,14,3
...,...,...,...,...,...,...,...
95,PR00095,M0095,P0095,2026-12-14 19:06:10,Nights,14,8
96,PR00096,M0096,P0096,2026-03-19 12:43:34,Nights,23,10
97,PR00097,M0097,P0097,2026-11-21 19:42:24,Nights,22,11
98,PR00098,M0098,P0098,2026-05-22 11:42:28,Morning,15,12
99,PR00099,M0099,P0099,2026-10-10 11:58:28,Nights,19,4

In [1]:
print("Idrees is King")

Idrees is King

In [2]:
#1. Maintenance.csv

# maintenance_id
# machine_id
# maintenance_date
# maintenance_type
# downtime_hours
# maintenance_cost

In [26]:

maintenance_id = [f"MT000{x}" for x in range(100)] #MT0001
machine_id
maintenance_date = [ d + pd.Timedelta(days= random.randint(1,100))
                    for d in installation_date]
maintenance_date

maintenance_t = ["Preventive","Corrective","Predictive"]
maintenance_type = [random.choice(maintenance_t) for _ in range(100)]
maintenance_type


downtime_rules = {
    "Preventive": (1, 4),
    "Predictive": (1, 3),
    "Corrective": (3, 12)
}
downtime_hours = [
    round(random.uniform(downtime_rules[b][0],downtime_rules[b][1]),1)
    for b in maintenance_type
]

maintenance_ = {
        "Preventive": (200, 800),
        "Predictive": (3000, 10000),
        "Corrective": (8000, 30000)
}

maintenance_cost = [
    round(random.uniform(maintenance_[m][0],maintenance_[m][1]),1)
    for m in maintenance_type
]

In [27]:
maintenance = pd.DataFrame({
    'maintenance_id':maintenance_id,
    'machine_id':machine_id,
    'maintenance_date':maintenance_date,
    'maintenance_type':maintenance_type,
    'downtime_hours':downtime_hours,
    'maintenance_cost':maintenance_cost
})

maintenance.to_csv('Maintenance.csv',index= False)

In [28]:
maintenance.shape

(100, 6)

In [29]:
# Quality_Inspections

# inspection_id
# production_id
# inspection_date
# inspected_units
# defective_units
# defect_type

In [33]:
inspection_id = [f"Q000{x}" for x in range(100)] #Q0001
production_id = [f"PR000{x}" for x in range(100)] #PR0001
inspection_date = [
    d + pd.Timedelta(days=random.randint(0, 2))
    for d in production_date
]

defect_ty = ['Surface Defect','Dimensional Error','Assembly Error']
defect_type = [random.choice(defect_ty) for x in range(100)]

In [39]:
units_produced = [
    random.randint(50, 200)
    for _ in range(100)
]

inspected_units = [
    random.randint(int(u * 0.7), u)
    for u in units_produced
]

defective_units = [
    random.randint(0, int(i * 0.10))
    for i in inspected_units
]

In [40]:
Quality_Inspections = pd.DataFrame({
    'inspection_id':inspection_id,
    'production_id':production_id,
    'inspection_date':inspection_date,
    'inspected_units':inspected_units,
    'inspected_units':inspected_units,
    'inspected_units':inspected_units,
    'inspected_units':inspected_units,
    'inspected_units':inspected_units,
    'defective_units':defective_units,
    'defective_units':defective_units,
    'defective_units':defective_units,
    'defect_type':defect_type
})

Quality_Inspections

,inspection_id,production_id,inspection_date,inspected_units,defective_units,defect_type
0,Q0000,PR0000,2026-07-17 10:51:26,123,11,Dimensional Error
1,Q0001,PR0001,2026-04-01 11:04:02,53,3,Surface Defect
2,Q0002,PR0002,2026-09-25 02:03:55,81,3,Assembly Error
3,Q0003,PR0003,2026-06-12 05:26:49,134,0,Assembly Error
4,Q0004,PR0004,2026-07-20 12:32:14,86,2,Surface Defect
...,...,...,...,...,...,...
95,Q00095,PR00095,2026-06-04 09:54:43,164,0,Dimensional Error
96,Q00096,PR00096,2026-07-04 23:09:18,55,0,Assembly Error
97,Q00097,PR00097,2026-12-18 23:21:27,89,3,Dimensional Error
98,Q00098,PR00098,2026-08-24 22:52:44,143,10,Dimensional Error
99,Q00099,PR00099,2026-02-01 18:12:56,64,6,Dimensional Error

In [41]:
Quality_Inspections.to_csv('Quality_Inspections.csv',index = False)